version: '3.8'

services:
  web:
    build: .
    command: gunicorn resume_app.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env